title:            SKiDL
description:      Python &rarr; Circuits
logo:             logo.png
disqus_shortname: skidl
share:            true
dropcap:	   true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	 https://xesscorp.github.io/skidl/docs/_site
#url: http://127.0.0.1:4000


# Owner/author information
owner:
  name:           XESS Corp.
  avatar:         xesscorp.png
  email:          skidl@xess.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Manufacturer of FPGA development boards.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        xesscorp
  github:         xesscorp    
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    https://plus.google.com/u/0/+AmeyJadiye

author1:
  name: Dave Vandenbout
  photo: devb-pic.jpg
  email: devb@xess.com
  twitter: devbisme
  description: Relax, I do this stuff for a living.


# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-46791108-1
#google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Blog
    url: /blog
  - title: API
    url: /api.html
  - title: Github
    url: "http://github.com/xesscorp/skidl"
    external: true
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    US/Eastern
future:      true
#rouge: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

collections:
  pages:
    output: true
    title: Pages

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
- jemoji
- octopress-paginate
- octopress-image-tag
#- jekyll-paginate
